const String target = "geniui";
const String file = "geniui/pubspec.yaml";
const String stub = """
name: geniui
description: Tailwind CSS like styling package (GeniUI) generated by the GeniUX.
version: 0.6.1
homepage: https://github.com/thedevsbuddy/geniux

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

""";
